### ISSUE TITLE
Spam!

### ISSUE THREAD

**Issue by SOF3** [Bamuel/SOFe-Generator#1]
Your web design is vulnerable to spam! You can send requests with different usernames on the server, or even use a dictionary attack. Without proper rate-limiting, one can create so many files in your directory.

Actually, the spam already happened. Execute `ls` on your server directory and sort the lines to see some of the longest lines. Some hints from the-guy-who-forgot-to-patent-his-profile-pic!

Via api.github.com

**Comment by Bamuel** [comment]
The web design was created to troll you in the process of creating a new avatar. about the server issue, the image files are so small that it wont affect unless you dictionary attack it for afew months.

![image](https://user-images.githubusercontent.com/6744113/40214959-23206378-5aa1-11e8-9f9e-e1d5eecbd424.png)
eyyy i see you
